services:
  convert_file:
    container_name: convert_file_container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # ถ้าไม่ต้องการ renew-hook ให้ใช้คำสั่งด้านล่างแทน
    # entrypoint: >
    #   /bin/sh -c "trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait \$!; done;"
    #
    # ตัวอย่างที่มี renew-hook (เช่น restart nginx container หลังต่ออายุสำเร็จ)
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --quiet --renew-hook 'docker-compose restart nginx'; sleep 12h & wait \$!; done;""

  nginx:
    image: nginx:lates
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - convert_file
      - certbot
    restart: unless-stopped


