events {
    worker_connections 1024;
}

http {
    upstream convert-file {
        server convert_file:3000;
    }

    server {
        listen 80;
        listen [::]:80;

        server_name dcsa-daikin.com;

        location / {
            proxy_pass http://convert-file;
        }

    }

    server {
        listen 443 ssl;
        http2 on;
        listen [::]:443 ssl http2;

        server_name dcsa-daikin.com;

        location / {
            proxy_pass http://convert-file;
        }
    }
}